### ISSUE TITLE
Send Game Entry Link

### ISSUE THREAD

**Issue by spencerhenze** [RiverMerrill/vue-pong.lb#16] opened 2018-09-28 02:37 UTC
User can send link to unfinished game entry to opponent
Opponent can click the link, finish the form, and submit the match

Needs to support:
Persist unfinished game entries.
Generate a link to the unfinished game entry.

**Comment by daisiev** [comment] 2018-09-28 02:38
Duplicate of #7

**Closed as completed** 2018-09-28 02:38 UTC
Labels: duplicate
